# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "departments", :force => true do |t|
    t.column "location_id", :integer, :null => false
    t.column "name", :string, :null => false
  end

  create_table "employees", :force => true do |t|
    t.column "job_id", :integer, :null => false
    t.column "department_id", :integer, :null => false
    t.column "salary", :integer, :null => false
    t.column "commission", :integer, :null => false
    t.column "first_name", :string, :null => false
    t.column "last_name", :string, :null => false
    t.column "email", :string, :null => false
  end

  create_table "jobs", :force => true do |t|
    t.column "title", :string
    t.column "min_salary", :integer, :null => false
    t.column "max_salary", :integer, :null => false
  end

  create_table "locations", :force => true do |t|
    t.column "street", :string, :null => false
    t.column "code", :integer, :null => false
    t.column "city", :string, :null => false
  end

end
